version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    volumes:
      - ./frontend/react-app:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
